# Generated by Django 3.2.9 on 2021-11-11 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('data_lancamento', models.DateTimeField()),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rate', models.IntegerField()),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='serie.serie')),
            ],
        ),
    ]
