# Generated by Django 3.2.9 on 2021-11-11 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('fillerOuCanon', models.BooleanField()),
                ('numeroEpisodio', models.IntegerField()),
                ('serieEpisodio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='serie.serie')),
            ],
        ),
    ]
