# Generated by Django 3.2.9 on 2021-11-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0003_auto_20211111_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodio',
            name='video',
            field=models.FileField(blank=True, upload_to='video/%y'),
        ),
    ]
