# Generated by Django 3.2.9 on 2021-11-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0005_alter_episodio_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodio',
            name='video',
            field=models.FileField(blank=True, upload_to='video/%y'),
        ),
    ]
