# Generated by Django 3.2.9 on 2021-11-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0006_alter_episodio_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='data_lancamento',
            field=models.DateField(),
        ),
    ]
