# Generated by Django 3.2.9 on 2021-11-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0008_alter_anime_data_lancamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='data_lancamento',
            field=models.DateTimeField(blank=True),
        ),
    ]
