# Generated by Django 3.2.9 on 2021-11-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0010_alter_anime_data_lancamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episodio',
            name='fillerOuCanon',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='rate',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='episodio',
            name='numeroEpisodio',
            field=models.PositiveBigIntegerField(),
        ),
    ]
