# Generated by Django 3.2.9 on 2021-11-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0011_auto_20211125_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='review',
            field=models.TextField(max_length=255),
        ),
    ]
