# Generated by Django 3.2.9 on 2021-11-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0012_alter_comentario_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='categoria',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='anime',
            name='descricao',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='anime',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='review',
            field=models.TextField(max_length=500),
        ),
    ]
