# Generated by Django 3.2.9 on 2021-11-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0013_auto_20211125_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='episodio',
            name='numeroEpisodio',
            field=models.IntegerField(),
        ),
    ]
