name: Aplicação Django


on: [pull_request]

jobs:
  build:
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENV: 1
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Instalar Dependencias
      run: |
        pip install Django
    - name: Rodar Testes Automáticos
      run: | 
        python3 manage.py test
